server:
  port: 7070

spring:
  application:
    name: olive-gateway-server    
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE

#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:            
        - id: do-login
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/doLogin
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/doLogin, /olive/core-user-login
            
        - id: refresh-token
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/refreshToken
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/refreshToken, /olive/reFresh-token  
            
        - id: change-password
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/changePassword
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/changePassword, /olive/change-password
         
        - id: edit-profile
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/editProfile
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/editProfile, /olive/edit-profile
        
        - id: reset-password
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/resetPassword
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/resetPassword, /olive/reset-password
        
        - id: forgot-password
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/forgotPassword
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/forgotPassword, /olive/forgot-password
        
        - id: change-myPic
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/updateMyPic
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/updateMyPic, /olive/change-myPic
        
        - id: profile
          uri: lb://olive-core-user
          predicates:
            - Path=/api/v1.0/myProfile
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1.0/myProfile, /olive/get-myProfile
        
        - id: foundation-get-org
#          uri: 'http://localhost:7072'
          uri: lb://olive-foundation-server
          predicates:
            - Path=/api/org/**
            - Method=GET
            - Query=id
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api(?<segment>/?.*), $\{segment}


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"
          
#eureka:
#  client:
#    region: default
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: http://localhost:7074/eureka/
      
logging:
#  level:
#    root: trace
  file:
    name: ./logs/olive-gateway-server.log
    

