server:
  port: 8001
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
    defaultZone: http://localhost/8001/eureka
